---
# The city name
CITY_NAME: Carcosa

# General size, in meters
CITY_SIZE_X: 300
CITY_SIZE_Y: 300

# Explicitly set population.  Use "null" to calculate based on city area
INHABITANTS: null

# Wealth of the city: 1=poor, 10=rich
WEALTH: 6

# Force certain special buildings
PLACES: [ 'CASTLE', 'SANCTUARY', 'CHURCH' ]

# Resources
RESOURCES:
- WOOD
- FISH
- LEATHER
- HORSE
- WALL
  #- PIG
  #- CAVE
  #- WOLL
  #- WALL
  #- RIVERX
  #- RIVERY


# Largest dimension of a house (1px=0.5m)
MAX_PLACE_SIZE: 20
# Smallest dimension of the biggest house (1px=0.5m)
MIN_PLACE_SIZE: 6

# Default color for buildings
DEFAULT_COLOR: '#505050'

WOOD_SPREADING: 3
DEFENSE: 1

