---
# The city name
CITY_NAME: Megatown

# General size, in meters
CITY_SIZE_X: 300
CITY_SIZE_Y: 600

# Explicitly set population.  Use "null" to calculate based on city area
INHABITANTS: null

# Wealth of the city: 1=poor, 10=rich
#WEALTH: 6

# Force certain special buildings
#PLACES: [ 'CASTLE', 'SANCTUARY', 'CHURCH' ]

# Resources
RESOURCES:
- WOOD
- FISH
- LEATHER
- HORSE
- WALL
- PIG
- CAVE
- WOOL
- WALL
- RIVERX
- RIVERY

